name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install toolchain
      uses: numworks/setup-arm-toolchain@2020-q2

    - name: Install dependencies
      run: make

    - name: Run check
      run: make check

    - name: Save public folder
      uses: actions/upload-artifact@v2
      with:
        name: nofrendo
        path: output/nofrendo.nwa
      
    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v3
